package main

import (
	"encoding/json"
	"fmt"
)

type AutoGenerated struct {
	Age   int    `json:"age"`
	Name  string `json:"name"`
	Child []int  `json:"child"`
}

func main() {
	jsonStr1 := `[1,2,3]`
	var s []int
	json.Unmarshal([]byte(jsonStr1), &s)
	fmt.Println(s) // [1 2 3]
	jsonStr2 := `[3,4,5,7,8,9]`
	json.Unmarshal([]byte(jsonStr2), &s)
	fmt.Println(s) // [3 4 5 7 8 9]

	jsonStr3 := `{"age": 14,"name": "potter", "child":[1,2,3]}`
	a := AutoGenerated{}
	json.Unmarshal([]byte(jsonStr3), &a)
	aa := a.Child
	fmt.Println(aa) // [1 2 3]
	jsonStr4 := `{"age": 12,"name": "potter", "child":[3,4,5,7,8,9]}`
	json.Unmarshal([]byte(jsonStr4), &a)
	fmt.Println(aa) // [3 4 5]
}
